type RPCErrorStrings =
	| 'CAPTURE_SHORTCUT_ALREADY_LISTENING'
	| 'GET_GUILD_TIMED_OUT'
	| 'INVALID_ACTIVITY_JOIN_REQUEST'
	| 'INVALID_ACTIVITY_SECRET'
	| 'INVALID_CHANNEL'
	| 'INVALID_CLIENTID'
	| 'INVALID_COMMAND'
	| 'INVALID_ENTITLEMENT'
	| 'INVALID_EVENT'
	| 'INVALID_GIFT_CODE'
	| 'INVALID_GUILD'
	| 'INVALID_INVITE'
	| 'INVALID_LOBBY'
	| 'INVALID_LOBBY_SECRET'
	| 'INVALID_ORIGIN'
	| 'INVALID_PAYLOAD'
	| 'INVALID_PERMISSIONS'
	| 'INVALID_TOKEN'
	| 'INVALID_USER'
	| 'LOBBY_FULL'
	| 'NO_ELIGIBLE_ACTIVITY'
	| 'OAUTH2_ERROR'
	| 'PURCHASE_CANCELED'
	| 'PURCHASE_ERROR'
	| 'RATE_LIMITED'
	| 'SELECT_CHANNEL_TIMED_OUT'
	| 'SELECT_VOICE_FORCE_REQUIRED'
	| 'SERVICE_UNAVAILABLE'
	| 'TRANSACTION_ABORTED'
	| 'UNAUTHORIZED_FOR_ACHIEVEMENT'
	| 'UNKNOWN_ERROR'

type RPCCloseStrings =
	| 'CLOSE_NORMAL'
	| 'CLOSE_UNSUPPORTED'
	| 'CLOSE_ABNORMAL'
	| 'INVALID_CLIENTID'
	| 'INVALID_ORIGIN'
	| 'RATELIMITED'
	| 'TOKEN_REVOKED'
	| 'INVALID_VERSION'
	| 'INVALID_ENCODING'

type RelationshipStrings = 'NONE' | 'FRIEND' | 'BLOCKED' | 'PENDING_INCOMING' | 'PENDING_OUTGOING' | 'IMPLICIT'

export const RPCErrors: Record<RPCErrorStrings, number> = {
	CAPTURE_SHORTCUT_ALREADY_LISTENING: 5004,
	GET_GUILD_TIMED_OUT: 5002,
	INVALID_ACTIVITY_JOIN_REQUEST: 4012,
	INVALID_ACTIVITY_SECRET: 5005,
	INVALID_CHANNEL: 4005,
	INVALID_CLIENTID: 4007,
	INVALID_COMMAND: 4002,
	INVALID_ENTITLEMENT: 4015,
	INVALID_EVENT: 4004,
	INVALID_GIFT_CODE: 4016,
	INVALID_GUILD: 4003,
	INVALID_INVITE: 4011,
	INVALID_LOBBY: 4013,
	INVALID_LOBBY_SECRET: 4014,
	INVALID_ORIGIN: 4008,
	INVALID_PAYLOAD: 4000,
	INVALID_PERMISSIONS: 4006,
	INVALID_TOKEN: 4009,
	INVALID_USER: 4010,
	LOBBY_FULL: 5007,
	NO_ELIGIBLE_ACTIVITY: 5006,
	OAUTH2_ERROR: 5000,
	PURCHASE_CANCELED: 5008,
	PURCHASE_ERROR: 5009,
	RATE_LIMITED: 5011,
	SELECT_CHANNEL_TIMED_OUT: 5001,
	SELECT_VOICE_FORCE_REQUIRED: 5003,
	SERVICE_UNAVAILABLE: 1001,
	TRANSACTION_ABORTED: 1002,
	UNAUTHORIZED_FOR_ACHIEVEMENT: 5010,
	UNKNOWN_ERROR: 1000,
}

export const RPCCloseCodes: Record<RPCCloseStrings, number> = {
	CLOSE_NORMAL: 1000,
	CLOSE_UNSUPPORTED: 1003,
	CLOSE_ABNORMAL: 1006,
	INVALID_CLIENTID: 4000,
	INVALID_ORIGIN: 4001,
	RATELIMITED: 4002,
	TOKEN_REVOKED: 4003,
	INVALID_VERSION: 4004,
	INVALID_ENCODING: 4005,
}

export const LobbyTypes: Record<'PRIVATE' | 'PUBLIC', number> = {
	PRIVATE: 1,
	PUBLIC: 2,
}

export const RelationshipTypes: Record<RelationshipStrings, number> = {
	NONE: 0,
	FRIEND: 1,
	BLOCKED: 2,
	PENDING_INCOMING: 3,
	PENDING_OUTGOING: 4,
	IMPLICIT: 5,
}
